import { FormInputIcon, UserCog2 } from "lucide-react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import BlurBackground from "~/ui/blur-backgrounds";
import Button from "~/ui/buttons";

import { api } from "~/utils/api";

import Header from "~/features/header";
import Count from "~/features/counter-animation";
import NumberAnimation from "~/features/counter-animation";
import Link from "next/link";

export default function Home() {
  // const users = api.example.getAll.useQuery();
  const { data: sessionData } = useSession();
  const getCount = api.home.getdaysCount.useQuery();
  return (
    <>
      <Head>
        <title>RAMP | About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlurBackground />

      <div className=" flex min-h-screen w-full  flex-col items-center justify-between gap-5 overflow-hidden bg-secondary transition-colors duration-1000 ">
        <section
          dir="rtl"
          className="mx-auto flex max-w-[980px] flex-col items-center  gap-7 py-8 md:py-12 md:pb-8 lg:py-24 lg:pb-20"
        >
          <h1 className="text-5xl font-bold text-primary">
            نرم افزار جامع تجزیه تحلیل و آنالیز داده های پرسنل
          </h1>
          <p className="max-w-[550px] text-justify text-primary/80 ">
            کلیه اطلاعات پایه و مدیریت مورد نیاز همانند انواع خدمت، پوشش های
            بیمه ای ، تعرفه های درمانی و ارزیابی ، اطلاعات کاربران و مراجع
            درمانی جهت نظارت بر فعالیت سامانه و کلیه بخش های زیر مجموعه آن از
            طریق این پنل صورت می گیرد.
          </p>
        </section>
      </div>
    </>
  );
}
