import { FormInputIcon, UserCog2 } from "lucide-react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import BlurBackground from "~/ui/blur-backgrounds";
import Button from "~/ui/buttons";

import { api } from "~/utils/api";

import Header from "~/features/header";
import Count from "~/features/counter-animation";
import NumberAnimation from "~/features/counter-animation";
import Link from "next/link";

export default function Home() {
  // const users = api.example.getAll.useQuery();
  const { data: sessionData } = useSession();
  const getCount = api.home.getdaysCount.useQuery();
  return (
    <>
      <Head>
        <title>RAMP | About</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlurBackground />

      <div className=" flex min-h-screen w-full  flex-col items-center justify-between gap-5 overflow-hidden bg-secondary transition-colors duration-1000 ">
        <section
          dir="rtl"
          className="mx-auto flex max-w-[980px] flex-col items-center  gap-7 py-8 md:py-12 md:pb-8 lg:py-24 lg:pb-20"
        >
          <h1 className="text-5xl font-bold text-primary">
            نرم افزار جامع تجزیه تحلیل و آنالیز داده های پرسنل
          </h1>
          <p className="text-justify text-xl leading-10 text-primary/80 ">
            شرکت آتیه سازان امید نسل امروز از سال 1397، فعالیت خود را در حوزه
            ارزیابی آغاز کرده است. همکاری عمده این شرکت با بیمه گر دی بوده و در
            30 استان کشور شعبه ارزیابی دارد. از آنجایی که بیمه گر دی از سامانه
            «رسا سلامت» برای ثبت، ارزیابی و پرداخت بیمه‌های درمان استفاده
            می‌کند، به منظور ارائه بهتر خدمات به بیمه شدگان و افزایش رضایتمندی
            بیمه گر و بیمه گذار لازم است عملکرد شعب ارزیابی از طریق گزارشات این
            سامانه رصد گردد. با توجه به اینکه گزارش‌های دریافتی از سامانه رسا به
            صورت داده‌های خام است و اطلاعات بیشتری درباره عملکرد پرسنل و شعب
            ارزیابی ارائه نمی‌کند، به همین دلیل بر آن شدیم تا با بهره گیری از
            نرم افزارهای داده کاوی از جمله power bi، داده‌های حاصل از این
            گزارشات را آنالیز کرده و دانش مورد نیاز مدیران ارشد بیمه دی، شرکت
            آتیه سازان امید نسل امروز و شعب ارزیابی را در اختیار ایشان قرار
            دهیم.
          </p>
        </section>
      </div>
    </>
  );
}
