services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - DATABASE_URL=sqlserver://5.202.179.158:5090;database=RAMP_Vision;user=admin;password=Mohammad@2525;trustServerCertificate=true;encrypt=true
        - NEXTAUTH_SECRET=your_actual_secret_here
        - NEXTAUTH_URL=http://localhost:3000
        - SQL_USER=admin
        - SQL_PASSWORD=Mohammad@2525
        - SQL_SERVERIP=5.202.179.158
        - SQL_PORT=5090
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlserver://5.202.179.158:5090;database=RAMP_Vision;user=admin;password=Mohammad@2525;trustServerCertificate=true;encrypt=true
      - NEXTAUTH_SECRET=your_actual_secret_here
      - NEXTAUTH_URL=http://localhost:3000
      - SQL_USER=admin
      - SQL_PASSWORD=Mohammad@2525
      - SQL_SERVERIP=5.202.179.158
      - SQL_PORT=5090
    restart: unless-stopped
    networks:
      - ramp-network

networks:
  ramp-network:
    driver: bridge
