"use client";
import {
  BuildingIcon,
  FormInputIcon,
  PercentDiamondIcon,
  SaveIcon,
  UserCog2,
  UserSearchIcon,
} from "lucide-react";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import BlurBackground from "~/ui/blur-backgrounds";
import Button from "~/ui/buttons";

import { api } from "~/trpc/react";

import Header from "~/features/header";
import Count from "~/features/counter-animation";
import NumberAnimation from "~/features/counter-animation";
import Link from "next/link";
import AreaChartFake from "~/features/fake-charts/area";
import ChevronLeftIcon from "~/ui/icons/chervons/chevron-left";
import ThreeDotsWave from "~/ui/loadings/three-dots-wave";
import { twMerge } from "tailwind-merge";
import Image from "next/image";

import { PowerLineMobile } from "~/ui/icons/power-lines/mobile";
import H2 from "~/ui/heading/h2";
import { PowerLine } from "~/ui/icons/power-lines/test";
import { DiagramSVG } from "~/resources/diagram";

function Card({ value = -1 }) {
  return (
    <div className=" text-primary">
      <p>
        تا کنون{" "}
        <span className="text-2xl text-accent">
          {value < 0 ? "..." : value}
        </span>{" "}
        روز، گزارش دریافت شده است
      </p>
    </div>
  );
}

function FloatDiv({ className }) {
  return <div className={twMerge("opacity-0", className)} />;
}

export default function Home() {
  // const users = api.example.getAll.useQuery();
  const { data: sessionData } = useSession();
  const getCount = api.home.getdaysCount.useQuery();
  return (
    <>
      <Head>
        <title>RAMP | Vision</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlurBackground />

      <div className=" flex min-h-screen w-full flex-col items-center justify-center  overflow-hidden bg-secondary py-5 transition-colors duration-1000 ">
        <section
          dir="rtl"
          className=" relative mx-auto flex h-[70vh]  max-w-[1000px] flex-col items-center justify-center gap-7 p-5"
        >
          <div
            dir="rtl"
            className=" relative mx-auto flex  max-w-[1000px] flex-col items-center justify-center gap-7 p-5"
          >
            <div className=" hidden items-center justify-center gap-5 text-primary lg:flex">
              <span className="flex items-center justify-center rounded-full bg-teal-900 px-2 py-0.5 text-sm text-teal-300">
                جدید
              </span>
              <p className="text-primary/60">
                <span className="text-primary">ویژگی</span> های نسخه جدید، سرعت
                بهتر در مقایسه بیشتر، بهبود امکانات آنالیز و اضافه شدن گزارش
                گیری ماهانه.
              </p>
              <Link
                href={"/about"}
                className="flex items-center justify-center gap-2 rounded-full border border-gray-700/50 bg-secondary px-4 py-1 text-primary"
              >
                بیشتر بخوانید
                <ChevronLeftIcon className="h-3 w-3 fill-none stroke-primary stroke-2" />
              </Link>
            </div>
            {/* mobile */}
            <Link
              href={"/about"}
              className="flex items-center justify-center gap-2 rounded-full border border-gray-700/50 bg-secondary py-1 pl-2 pr-1 text-primary lg:hidden"
            >
              <span className="flex items-center justify-center rounded-full bg-teal-900 px-2 py-0.5 text-sm text-teal-300">
                جدید
              </span>
              <p className="text-sm text-primary/60">
                <span className="text-primary">ویژگی</span> ها و امکانات نسخه
                جدید
              </p>
              <ChevronLeftIcon className="h-3 w-3 fill-none stroke-primary stroke-2" />
            </Link>
            <FloatDiv
              className="line_height_animation_120 absolute -top-[10%] 
              left-0 h-[120%] w-[1px] bg-gradient-to-b  from-transparent from-0% via-primary/30 via-50% to-transparent to-100%  "
            />
            <FloatDiv
              className="line_height_animation_120 absolute -top-[10%] 
              right-0 h-[120%] w-[1px] bg-gradient-to-b  from-transparent from-0% via-primary/30 via-50% to-transparent to-100%  "
            />
            <h1 className="relative p-5 text-center text-4xl font-bold text-primary">
              <FloatDiv
                className="line_width_animation_140  absolute -left-[20%] 
                top-0 h-[1px] w-[140%] bg-gradient-to-r  from-transparent from-0% via-primary/30 via-50% to-transparent to-100%  "
              />
              نرم افزار جامع مدیریت و تحلیل عملکرد پرسنل و شعب
            </h1>
            <div className="relative max-w-[550px] p-5 text-center text-primary/80 ">
              این سامانه جهت سهولت در تحلیل عملکرد شعب و پرسنل و محاسبه درصد
              خسارت بر اساس استاندارد های تعیین شده طراحی گردیده است
              <FloatDiv className="line_width_animation_215 absolute -left-[57.5%] bottom-0 h-[1px] w-[215%] bg-gradient-to-r  from-transparent from-0% via-primary/30 via-50% to-transparent to-100%  " />
            </div>
            <div className="relative flex w-auto flex-col items-center justify-center gap-4  p-5 ">
              <FloatDiv
                className="line_height_animation_160 absolute -top-[25%] 
                right-0 h-[160%] w-[1px] bg-gradient-to-b  from-transparent from-0% via-primary/50 via-50% to-transparent to-100%  "
              />
              <FloatDiv
                className="line_height_animation_160 absolute -top-[25%] 
                left-0 h-[160%] w-[1px] bg-gradient-to-b  from-transparent from-0% via-primary/50 via-50% to-transparent to-100%  "
              />
              <div className="relative flex items-center justify-between gap-4  ">
                <Link
                  className="focus-visible:ring-ring inline-flex items-center justify-center whitespace-nowrap rounded-md bg-primary px-4 py-2 text-sm  font-medium text-secondary shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 disabled:pointer-events-none disabled:opacity-50"
                  href={"about"}
                >
                  درباره RAMP
                </Link>

                {!sessionData?.user && (
                  <Button
                    className="flex  items-center justify-center gap-2 rounded-lg border border-accent  stroke-accent p-0 px-6 py-1.5  text-primary"
                    onClick={
                      sessionData ? () => void signOut() : () => void signIn()
                    }
                  >
                    <span className="">ورود</span>
                  </Button>
                )}
              </div>
              <Card value={!getCount.data ? -1 : getCount.data} />
            </div>
          </div>
        </section>
        <section className="pt-20 md:p-0">
          <Image
            className=""
            src={"/svg/diagram-main.svg"}
            width={1000}
            height={720}
            alt="dashboard"
          />
          {/* <DiagramSVG /> */}
        </section>
        <section className="relative flex  w-full flex-col items-center justify-center gap-4 bg-secondary">
          <H2 className="sizeforh2 pt-10 text-center">ویژگی های کلی سامانه</H2>
          <div className="bg-shadow relative flex  w-full items-center justify-center  ">
            <PowerLine className="powerline mobileMax:hidden" />
            <PowerLineMobile className="powerlineMobile mobileMin:hidden" />

            {/* absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2  */}
            <div className="foundation_cpu__ciXpm absolute left-1/2 top-[25%] flex h-16 w-[180px] -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-md bg-secbuttn text-red-600 mobileMin:top-[calc(50%+9px)]">
              <span className="text-lg text-accent"> پردازش</span>
              <div data-cpu-shine="true"></div>
              <div data-connectors="true" data-side="left">
                <span data-connector="true"></span>
                <span data-connector="true"></span>
              </div>
              <div data-connectors="true" data-side="top">
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
              </div>
              <div data-connectors="true" data-side="bottom">
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
                <span data-connector="true"></span>
              </div>
              <div data-connectors="true" data-side="right">
                <span data-connector="true"></span>
                <span data-connector="true"></span>
              </div>
            </div>
          </div>
        </section>
        <section className="flex w-full flex-col items-center justify-center gap-5 md:w-11/12 md:flex-row md:items-stretch">
          <InfoCard
            className="blueShadow text-cyan-500"
            title="محاسبه درصد خسارت"
            icon={
              <>
                <PercentDiamondIcon className="h-14 w-14 stroke-cyan-500" />
              </>
            }
          >
            از دیگر ویژگی های این سامانه می توان به دستیابی به گزارشات؛ حواله
            های عودتی نظارت، حواله های عودتی خسارت، محاسبه درصد انحراف حواله های
            خسارت و درصد حواله های ابطال شده به تفکیک استان اشاره کرد
          </InfoCard>
          <InfoCard
            className="redShadow text-rose-700"
            title="محاسبه عملکرد پرسنل"
            icon={
              <>
                <UserSearchIcon className="h-14 w-14 stroke-rose-700" />
              </>
            }
          >
            به منظور دستیابی به عملکرد پرسنل تمام وقت شعبه، فعالیت های صورت
            گرفته از ارزیابی اسناد بیمارستانی، ارزیابی اسناد دارویی، پذیرش و ثبت
            اولیه اسناد، ثبت ارزیابی با اسکن مدارک، تعداد پرونده ورودی،تعداد دپو
            و... بر اساس استانداردهای تعیین شده بررسی می گردد.
          </InfoCard>
          <InfoCard
            className="yellowShadow text-accent"
            title="محاسبه عملکرد کلی شعبه"
            icon={
              <>
                <BuildingIcon className="h-14 w-14 stroke-accent" />
              </>
            }
          >
            به منظور سنجش عملکرد هر شعبه عمکرد حاصل از پرسنل آن در چهار دسته
            عالی، خوب، متوسط و ضعیف ارزیابی می‌گردد. در صورتی که درصد عملکرد
            شعبه بیشتر از 90 باشد عملکرد شعبه عالی، در صورتی که بین 75 تا 90
            باشد عملکرد شعبه خوب، در صورتی که بین 60 تا 75 باشد عملکرد شعبه
            متوسط و در صورتی که دپو کمتر از 60 باشد، عملکرد شعبه ضعیف است.
          </InfoCard>
        </section>

        {/* <section className="flex w-9/12 items-center justify-center gap-2">
            <div className="w-full">
              <AreaChartFake />
            </div>
            <div className="w-full">
              <AreaChartFake />
            </div>
          </section> */}

        {/* 
          <Image
            className="absolute left-[1000px] top-20"
            src={"/images/dashboard.jpg"}
            width={1916}
            height={1080}
            alt="dashboard"
          /> */}
      </div>
    </>
  );
}

function InfoCard({ children, className = "", title = "عنوان", icon = <></> }) {
  return (
    <>
      <div
        dir="rtl"
        className={twMerge(
          "foundation_card__v7VKB  flex max-w-md flex-col items-center justify-start gap-4 rounded-lg  border border-secbuttn bg-secbuttn p-4",
          className,
        )}
      >
        <div className="flex w-full items-center justify-between">
          <h3 className="w-full text-right text-2xl font-bold text-inherit">
            {title}
          </h3>
          {icon}
        </div>
        <p className="text-justify text-primary">{children}</p>
      </div>
    </>
  );
}
